# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SafeZone' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SafeZone

  pod "SwiftSpinner"
  pod 'Alamofire', '~> 4.5'
  pod 'BHPhotoView', :git => 'https://github.com/benhurott/BHPhotoView'
  pod 'SCLAlertView'

end
